spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lingoace?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password:
      initial-size: 1
      min-idle: 1
      max-active: 50
      max-wait: 10000
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat
